@startuml
actor User
participant Main
participant Restaurant

User -> Main : Start application
Main -> Restaurant : displayRoleMenu(startMenu)
User -> Restaurant : selectRole(1 - Customer)
Restaurant -> Restaurant : customerMenu()

@enduml
